matrix:
  include:
    - language: objective-c
      osx_image: xcode9.4
      sudo: false
      env:
        - TRAVIS_NODE_VERSION: 12
      before_install:
        - nvm install $TRAVIS_NODE_VERSION
      install:
        - npm install -g cordova@latest
        - npm install
      before_script:
        - cordova platform add ios
      script:
        - node --version
        - npm --version
        - cordova build ios
        - zip -r release.zip platforms/ios/build/emulator/
        - mkdir Payload
        - cd Payload
        - mkdir HelloCordova.app
        - cd ..
        - cp -r platforms/ios/build/emulator/HelloCordova.app/ Payload/HelloCordova.app/
        - ls Payload/
        - zip -r HelloCordova.zip Payload
        - mv HelloCordova.zip HelloCordova.ipa
        - ls
      deploy:
        - provider: releases
          file_glob: true
          file:
            - release.zip
            - HelloCordova.ipa
          name: release-ios
          api_key:
            secure: $GITHUB_TOKEN
          skip_cleanup: true
          draft: true
    - sudo: required
      language: android
      jdk: oraclejdk8
      env:
        global:
          - TERM=dumb # Keep gradle from crapping all over the log
          - nodejs_version=12
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-android-support
          - extra-google-google_play_services

      before_install:
        - touch $HOME/.android/repositories.cfg
        - nvm install $nodejs_version
        - node --version
        - npm --version
        - gradle --version
      install:
        - npm install
      before_script:
        - npm install -g cordova
        - cordova platform add android
      script:
        - cordova build android
      deploy:
        - provider: releases
          file: platforms/android/app/build/outputs/apk/debug/app-debug.apk
          api_key:
            secure: $GITHUB_TOKEN
          skip_cleanup: true
          draft: true

