language: objective-c
osx_image: xcode9.4
sudo: false

env:
  - TRAVIS_NODE_VERSION: 12

before_install:
  - nvm install $TRAVIS_NODE_VERSION

install:
  - npm install -g cordova@latest
  - npm install

before_script:
  - cordova platform add ios
script:
  - node --version
  - npm --version
  - cordova build ios
  - ls platforms/ios/build/emulator/
  - zip -r release.zip platforms/ios/build/emulator/
  - ls

deploy:
  - provider: releases
    file_glob: true
    file: release.zip
    api_key:
      secure: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
